#********************************************************************************PATH********************************************************************************
# Output
output_dir: '../store/train_1'

# Data
train_path: '../data/train.csv'
val_path: '../data/val.csv'
test_path: '../data/test.csv'

# Checkpoint
use_train_checkpoint: False
train_checkpoint: '../store/train_1/checkpoint_01.pth'

#********************************************************************************TRAIN********************************************************************************
# Distributed training
distributed: False
dist_url: 'tcp://'
package: 'gloo'
num_gpu: 1

# Device
train_device: 'cuda:0'
eval_device: 'cuda:1'

# Param
batch_size: 8
max_epoch: 100
early_stop: 5

# Optimizer
eta: 0.00001

#********************************************************************************MODEL********************************************************************************
# Loss
loss:
  - loss_ce